const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.Follow,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.JavaScriptInEvents.EventSheet1_Event31_Act3,
		C3.JavaScriptInEvents.EventSheet1_Event32_Act2,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{IsGrinding: 0},
	{GrindSpeed: 0},
	{vecDir: 0},
	{canJump: 0},
	{Platform: 0},
	{Timer: 0},
	{Bullet: 0},
	{Sprite: 0},
	{Solid: 0},
	{tb: 0},
	{Keyboard: 0},
	{TiledBackground2: 0},
	{rail: 0},
	{TiledBackground: 0},
	{TiledBackground3: 0},
	{ScrollTo: 0},
	{camera: 0},
	{Follow: 0},
	{Sprite2: 0},
	{bg1: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{Sprite3: 0},
	{TiledBackground4: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{gametime: 0},
	{Sprite6: 0},
	{JOGAR: 0},
	{Sprite7: 0},
	{Mouse: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{menuback: 0},
	{Text5: 0},
	{menu: 0},
	{retry: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Audio: 0},
	{canDash: 0},
	{curDash: 0},
	{cameraX: 0},
	{cameraY: 0},
	{timer: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	tb: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	rail: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	camera: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	bg1: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	gametime: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	JOGAR: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	menuback: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	menu: class extends self.ITextInstance {},
	retry: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}