const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Exps.VectorY
	];
};
self.C3_JsPropNameTable = [
	{IsGrinding: 0},
	{GrindSpeed: 0},
	{vecDir: 0},
	{canJump: 0},
	{Platform: 0},
	{Timer: 0},
	{Bullet: 0},
	{Sprite: 0},
	{Solid: 0},
	{tb: 0},
	{Keyboard: 0},
	{TiledBackground2: 0},
	{rail: 0},
	{TiledBackground: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{ScrollTo: 0},
	{camera: 0},
	{canDash: 0},
	{curDash: 0},
	{cameraX: 0},
	{cameraY: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	tb: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	rail: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	camera: class extends self.ITiledBackgroundInstance {}
}